use wayland_protocols::wp::cursor_shape::v1::server::wp_cursor_shape_device_v1::Shape;

pub fn shape_to_name(shape: Shape) -> &'static str {
    match shape {
        Shape::Default => "default",
        Shape::ContextMenu => "context-menu",
        Shape::Help => "help",
        Shape::Pointer => "pointer",
        Shape::Progress => "progress",
        Shape::Wait => "wait",
        Shape::Cell => "cell",
        Shape::Crosshair => "crosshair",
        Shape::Text => "text",
        Shape::VerticalText => "vertical-text",
        Shape::Alias => "alias",
        Shape::Copy => "copy",
        Shape::Move => "move",
        Shape::NoDrop => "no-drop",
        Shape::NotAllowed => "not-allowed",
        Shape::Grab => "grab",
        Shape::Grabbing => "grabbing",
        Shape::EResize => "e-resize",
        Shape::NResize => "n-resize",
        Shape::NeResize => "ne-resize",
        Shape::NwResize => "nw-resize",
        Shape::SResize => "s-resize",
        Shape::SeResize => "se-resize",
        Shape::SwResize => "sw-resize",
        Shape::WResize => "w-resize",
        Shape::EwResize => "ew-resize",
        Shape::NsResize => "ns-resize",
        Shape::NeswResize => "nesw-resize",
        Shape::NwseResize => "nwse-resize",
        Shape::ColResize => "col-resize",
        Shape::RowResize => "row-resize",
        Shape::AllScroll => "all-scroll",
        Shape::ZoomIn => "zoom-in",
        Shape::ZoomOut => "zoom-out",
        Shape::DndAsk => "dnd-ask",
        Shape::AllResize => "all-resize",
        _ => "default",
    }
}
